# github dependabot config
version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

    # optional: automatically add labels to dependabot PRs
    labels:
      - "dependencies"

    # optional: automatically assign reviewers to prs
    reviewers:
      - "nothumanity"

    # optional: allow dependabot to update direct dependencies only
    allow:
      - dependency-type: "direct"

    # notify immediately for security updates
    open-pull-requests-limit: 3