# ----------------------------
# jekyll configuration
# ----------------------------
# site info
url: https://laaatte.github.io
title: Laaatte
description: GitHub Blog
lang: ko
timezone: asia/seoul

# assets version (css, favicon)
assets_version: 2604051

# open graph
og_type: Website
og_locale: ko_kr
og_image: /assets/og-image.png

# google analytics
google_analytics: G-8Y1W84B2CX

# sass settings
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass/layout
    - _sass/syntax

# markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# url structure
permalink: /:title

# collections (info, categories)
collections:
  info:
    output: true
    sort_by: order
  category:
    output: true

# default front matter
defaults:
  - scope:
      type: posts
    values:
      layout: page
      permalink: /:collection/:title
      show_article_header: true

  - scope:
      type: info
    values:
      layout: page
      permalink: /:name

  - scope:
      type: category
    values:
      layout: category
      permalink: /:collection/:name
      show_article_header: true