# ----------------------------
# jekyll configuration
# ----------------------------

# site info
url: https://nothumanity.github.io
title: nothumanity
description: jekyll blog
lang: ko
timezone: asia/seoul

# open graph
og_type: website
og_locale: ko_kr
# og_image: 

# google analytics
google_analytics: g-8y1w84b2cx

# plugins
plugins:
  - generate_posts_json  # custom plugin to generate posts.json automatically

# sass settings
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass/layout
    - _sass/syntax

# markdown & syntax highlighting
markdown: kramdown
kramdown:
  input: gfm
  syntax_highlighter: rouge

# url structure
permalink: /:title

# pagination settings
paginate: 10  # number of posts per page
paginate_path: /page:num/  # url for pagination pages

# collections (tabs, categories)
collections:
  tabs:
    output: true
    sort_by: order
  category:
    output: true

# default front matter
defaults:
  - scope:
      type: posts
    values:
      layout: page
      permalink: /:collection/:title
      page_type: post

  - scope:
      type: tabs
    values:
      layout: page
      permalink: /:collection/:name

  - scope:
      type: category
    values:
      layout: category
      permalink: /:collection/:name

  # add default for posts.json
  - scope:
      path: ""
      type: "posts"
    values:
      layout: null  # no layout for posts.json
      permalink: /posts.json  # path for posts.json file